### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ggonsalv35** [jroal/a2dp-connect2#10]
Could the icon/widget disconnect the device instead of disabling the A2DP profile?

**Comment by jroal** [comment]
It only connects and disconnects.  It does not disable A2DP profile.  Some Bluetooth devices support multiple Bluetooth profiles and when they see one disconnect but the others stay, they will disable until reset.  There is nothing I can do about that from an app standpoint as this behavior is in the receiving device.
