### ISSUE TITLE
Not working on Samsun s9 with android 8

### ISSUE THREAD

**Issue by Onanation** [jroal/a2dp-connect2#11]
Love this widget and it used to work on my s7 but it keeps turning off bluetooth on the new S9+

**Comment by jroal** [comment]
That is very odd as it only turns ON bluetooth if it was off when you clicked the button.

**Comment by jroal** [comment]
I have now made very significant changes to the widget since this post.  I will close this now.  There are many known problems with the widget.  I may just abandon it.  Fork this and work on fixing it if you are inclined and interested.  Good luck.
