### ISSUE TITLE
not working on android 5.0.1

### ISSUE THREAD

**Issue by pi-emotix** [jroal/a2dp-connect2#8]
a2dp connect does not work on android 5.0.1 . i have tried 2 samsung galaxy s4 phones with 5.0.1 .
It shows the device connecting tooltip but a2dp connection does not take place.

however it works without any issue on samsung phone with android 5.0

i have also to implement the code on my own but am facing the same issues.
It intermittantly connects to a2dp .i am also able to see the debug logs **"Proxy object connected"**
which can be found in android source file  **android.bluetooth.BluetoothA2dp** .

I am able to successfully connect to the a2dp device from the settings menu

**Comment by jroal** [comment]
This widget has changed significantly since this issue was posted. It no longer supports Android 5. I am closing this now.
